# Generated by Django 5.1.3 on 2024-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_news_siteconfiguration_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='description',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(max_length=200),
        ),
    ]
