# Generated by Django 5.1.3 on 2024-11-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leccion',
            name='modulo',
        ),
        migrations.AddField(
            model_name='leccion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
