# Generated by Django 5.1.3 on 2024-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_leccion_modulo_leccion_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='Default Notification Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
