# Generated by Django 5.1.3 on 2024-11-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_noticia_autor_noticia_destacado_noticia_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
