# Generated by Django 5.1.3 on 2024-11-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresousuario',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
