# Generated by Django 5.1.3 on 2024-11-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_leccion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacion',
            name='moderada',
            field=models.BooleanField(default=False),
        ),
    ]
