# Generated by Django 5.1.3 on 2024-11-27 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_testimonio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonio',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='testimonio',
            name='enlace_redes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='puesto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
