# Generated by Django 5.1.3 on 2024-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
