# Generated by Django 5.1.3 on 2024-11-30 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_blogpost_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='main_app.comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='voto_negativo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='voto_positivo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
