# Generated by Django 5.1.3 on 2024-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_comentario_padre_comentario_voto_negativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
