# Generated by Django 5.1.3 on 2024-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_comentario_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
