# Generated by Django 5.1.3 on 2024-12-01 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_suscriptor_reaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descripción optimizada para SEO. Máximo 160 caracteres.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título optimizado para SEO. Máximo 60 caracteres.', max_length=60, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reaccion',
            unique_together={('post', 'usuario')},
        ),
    ]
