# Generated by Django 5.1.3 on 2024-12-01 04:44

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_blogpost_meta_description_blogpost_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descripción optimizada para SEO. Máximo 160 caracteres.', max_length=160, null=True, validators=[main_app.models.validate_meta_description]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título optimizado para SEO. Máximo 60 caracteres.', max_length=60, null=True, validators=[main_app.models.validate_meta_title]),
        ),
    ]
