# Generated by Django 5.1.3 on 2024-12-01 05:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
