# Generated by Django 5.1.3 on 2024-12-01 05:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_blogpost_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
